### ISSUE TITLE
群晖ipv6table

### ISSUE THREAD

**Issue by Windman1320** [wangliangliang2/fix_synology_docker_ipv6#1]
请教一下大佬，docker开启 ip6table之后无法启动的问题是咋解决的

**Comment by wangliangliang2** [comment]
直接运行这个repo的master分支的fix.sh就修复了。
具体的看这个repo的readme.md

**Comment by Windman1320** [comment]
添加之后重启docker就这样了, service [pkgctl-Docker] restart failed, synoerr=[0x2000]
尝试过重启机器，同样无效
使用调试模式运行docker，错误日志如下：
`error="<nil>" notified=false state="STOPPING=1"
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables --wait -t nat -N DOCKER: iptables v1.6.0: can't initialize iptables table nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)
`

**Comment by wangliangliang2** [comment]
你先把中文的readme看完吧。你的版本应该不是我readme里面写的。

**Comment by Windman1320** [comment]
我的系统版本 DSM 6.2.2-24922 Update 4，看来出问题最有可能的就是系统版本了，有办法适配或者方便告知一下适配的方法么 感谢

**Comment by wangliangliang2** [comment]
自己编译一套。[issue](https://github.com/SynoCommunity/spksrc/issues/4713#issuecomment-1000017943)

**Comment by Windman1320** [comment]
除了 `nf_nat_masquerade_ipv6.ko` 这个组件外，其余的我都编译出来了，目前我的机器开启ipv6 配置能够正常启动
但我有点迷惑的是，ipv6 nat貌似生效有点问题， 只有mysql容器能够使用v6访问
执行`ipt6tables -t nat -nvL`后 输出如下：
```
Chain PREROUTING (policy ACCEPT 1 packets, 76 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 1 packets, 76 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 19 packets, 2112 bytes)
 pkts bytes target     prot opt in     out     source               destination
  121 12999 DEFAULT_OUTPUT  all      *      *       ::/0                 ::/0

Chain POSTROUTING (policy ACCEPT 19 packets, 2112 bytes)
 pkts bytes target     prot opt in     out     source               destination
  122 13081 DEFAULT_POSTROUTING  all      *      *       ::/0                 ::/0

Chain DEFAULT_OUTPUT (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER     all      *      *       ::/0                !::1                  ADDRTYPE match dst-type LOCAL

Chain DEFAULT_POSTROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination
    1    82 MASQUERADE  all      *      !docker0  fd00::/80            ::/0
    0     0 MASQUERADE  tcp      *      *       fd00::242:ac11:3     fd00::242:ac11:3     tcp dpt:3306

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all      docker0 *       ::/0                 ::/0
    0     0 DNAT       tcp      !docker0 *       ::/0                 ::/0                 tcp dpt:3306 to:[fd00::242:ac11:3]:3306
```

我很费解，不知道问题是否出现在`nf_nat_masquerade_ipv6.ko`这个模块，想请教一下您的该模块是怎么配置后才生成的，我在make menuconfig的时候把里面netfilter 以及ipv6相关的都试了一遍，也没有生成，网上搜了一圈也没有找到有用信息
PS: 参考mysql 容器的网络配置，查看后发现其监听了 `[::]` 和 `0.0.0.0`，我在修改其他容器的 `hostconfig.json` 配置后，也能够实现ipv6访问，ipv6 nat里面也有了其他端口的配置信息

**Comment by wangliangliang2** [comment]
20版本以上的docker 默认不再做 ipv6->ipv4 转换，要想访问ipv6端口的就要服务就要监听ipv6地址。

**Comment by wangliangliang2** [comment]
> 我很费解，不知道问题是否出现在`nf_nat_masquerade_ipv6.ko`这个模块，想请教一下您的该模块是怎么配置后才生成的，我在make menuconfig的时候把里面netfilter 以及ipv6相关的都试了一遍，也没有生成，网上搜了一圈也没有找到有用信息 PS: 参考mysql 容器的网络配置，查看后发现其监听了 `[::]` 和 `0.0.0.0`，我在修改其他容器的 `hostconfig.json` 配置后，也能够实现ipv6访问，ipv6 nat里面也有了其他端口的配置信息

20版本以上的docker 默认不再做 ipv6->ipv4 转换，要想访问服务的ipv6端口，服务就要监听ipv6地址

**Comment by Windman1320** [comment]
> 

所以有没有 nf_nat_masquerade_ipv6.ko 模块影响不大是吧

**Comment by wangliangliang2** [comment]
> 所以有没有 nf_nat_masquerade_ipv6.ko 模块影响不大是吧

是。ipv6和ipv4不一样。本身就没有nat的概念
